# Generated by Django 2.1.2 on 2018-10-31 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0007_auto_20181031_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('numero', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('fecha_inicio', models.DateTimeField()),
                ('estado', models.CharField(max_length=15)),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaBancaria',
            fields=[
                ('numero', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('banco', models.CharField(choices=[('bc', 'Banco de Chile'), ('be', 'Banco Estado')], max_length=50)),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaPrepago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, null=True)),
                ('saldo', models.CharField(max_length=50, null=True)),
                ('fecha_emision', models.CharField(max_length=50, null=True)),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Cliente')),
            ],
        ),
    ]
