# Generated by Django 2.1.2 on 2018-10-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetabancaria',
            name='banco',
            field=models.CharField(choices=[('be', 'Banco Estado'), ('bc', 'Banco de Chile')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tarjetaprepago',
            name='fecha_emision',
            field=models.DateTimeField(null=True),
        ),
    ]
