# Generated by Django 2.1.2 on 2018-10-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=20),
        ),
    ]
