# Generated by Django 2.1.2 on 2018-10-31 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20181031_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='comunaDomicilio',
            new_name='comuna_domicilio',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='comunaTrabajo',
            new_name='comuna_trabajo',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], max_length=20),
        ),
    ]
