# Generated by Django 2.1.2 on 2018-10-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20181031_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comuna_domicilio',
            field=models.CharField(choices=[('Lc', 'Las Condes'), ('lr', 'La Reina'), ('ññ', 'Ñuñoa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='comuna_trabajo',
            field=models.CharField(choices=[('Lc', 'Las Condes'), ('lr', 'La Reina'), ('ññ', 'Ñuñoa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tarjetabancaria',
            name='banco',
            field=models.CharField(choices=[('bc', 'Banco de Chile'), ('be', 'Banco Estado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=20),
        ),
    ]
