# Generated by Django 2.1.2 on 2018-10-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20181031_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comuna_domicilio',
            field=models.CharField(choices=[('ññ', 'Ñuñoa'), ('lr', 'La Reina'), ('Lc', 'Las Condes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='comuna_trabajo',
            field=models.CharField(choices=[('ññ', 'Ñuñoa'), ('lr', 'La Reina'), ('Lc', 'Las Condes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], max_length=20),
        ),
    ]
