# Generated by Django 2.1.2 on 2018-10-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20181031_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comuna_domicilio',
            field=models.CharField(choices=[('lr', 'La Reina'), ('Lc', 'Las Condes'), ('ññ', 'Ñuñoa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='comuna_trabajo',
            field=models.CharField(choices=[('lr', 'La Reina'), ('Lc', 'Las Condes'), ('ññ', 'Ñuñoa')], max_length=50),
        ),
    ]
