# Generated by Django 2.1.2 on 2018-10-31 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('numero_arriendo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('valor', models.IntegerField(null=True)),
                ('iva', models.IntegerField(null=True)),
                ('calificacion', models.IntegerField(null=True)),
                ('comentario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bicicleta', models.CharField(max_length=50, null=True)),
                ('año', models.IntegerField(null=True)),
                ('gps', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candado',
            fields=[
                ('numero_candado', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('C', 'Cerrado'), ('A', 'Abierto')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='candado',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonas.Zona'),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='numero_candado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonas.Candado'),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='id_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonas.Zona'),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='numero_bicicleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonas.Bicicleta'),
        ),
    ]
